language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - mkdir -p ${TRAVIS_BUILD_DIR}/tools
  - export PATH=${TRAVIS_BUILD_DIR}/tools/:$PATH
  - curl -L https://build.obolibrary.io/job/ontodev/job/robot/job/cmd-metrics/lastSuccessfulBuild/artifact/bin/robot.jar -o ${TRAVIS_BUILD_DIR}/tools/robot.jar 
  - curl -L https://raw.githubusercontent.com/ontodev/robot/v1.7.2/bin/robot -o ${TRAVIS_BUILD_DIR}/tools/robot
  - chmod +x ${TRAVIS_BUILD_DIR}/tools/robot
  - chmod +x ${TRAVIS_BUILD_DIR}/tools/robot.jar

script:
  - robot --version
  - python ./util/dashboard_config.py rundashboard -C dashboard-config.yml
